import configData from "./config.json";
import { cacheIdPrefix } from "./cacheId.js";

/**
 * Register (or deliberately don't register) the service worker.
 *
 * Three cases:
 *
 *  - Development: never. The service worker is only generated by
 *    `vite build`, and anything left over from a `vite preview` run is
 *    actively torn down here, so a stale worker can never be the reason the
 *    dev server is behaving oddly.
 *
 *  - OFFLINE.ENABLED false: don't register, and don't tear anything down
 *    either. The build emits a tombstone sw.js for that case; browsers with
 *    an existing registration check for an updated worker on navigation, find
 *    the tombstone, and it removes itself. Racing that from here would only
 *    confuse matters.
 *
 *  - Otherwise: register, with updateViaCache "none" so the worker script is
 *    never answered from the HTTP cache.
 */
export function registerServiceWorker() {
  if (!("serviceWorker" in navigator)) {
    return;
  }

  if (!import.meta.env.PROD) {
    unregisterInDevelopment();
    return;
  }

  if (configData.OFFLINE?.ENABLED !== true) {
    return;
  }

  const base = import.meta.env.BASE_URL;
  window.addEventListener("load", () => {
    navigator.serviceWorker
      .register(`${base}sw.js`, { scope: base, updateViaCache: "none" })
      .catch((error) => {
        // Offline support is an enhancement; the app works without it.
        console.error("Service worker registration failed:", error);
      });
  });
}

async function unregisterInDevelopment() {
  try {
    const registrations = await navigator.serviceWorker.getRegistrations();
    await Promise.all(registrations.map((registration) => registration.unregister()));
    if (typeof caches !== "undefined") {
      const prefix = `${cacheIdPrefix(configData.APP_ID)}-`;
      const names = await caches.keys();
      await Promise.all(
        names.filter((name) => name.startsWith(prefix)).map((name) => caches.delete(name))
      );
    }
  } catch (error) {
    console.warn("Could not clear service workers in development:", error);
  }
}
